project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

render: 
    - "*.qmd"
    - "*.ipynb"
    - "!cde_compute_edges_from_nodes.py"

title: "HRA: Cell Distance Analysis"
site-url: "https://cns-iu.github.io/hra-cell-distance-analysis"
description: "Cell Distance Analysis for Spatial Omics Datasets, primarily focused on vascular cells."

metadata-files: [nbdev.yml, sidebar.yml]