# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hra-cell-distance-analysis',
                'doc_host': 'https://cns-iu.github.io',
                'git_url': 'https://github.com/cns-iu/hra-cell-distance-analysis',
                'lib_path': 'hra_cell_distance_analysis'},
  'syms': { 'hra_cell_distance_analysis.core': { 'hra_cell_distance_analysis.core.foo': ( 'core.html#foo',
                                                                                          'hra_cell_distance_analysis/core.py')}}}
